apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["/bin/sh","-c","mkdir /data && touch /data/file1 && touch /data/file2 && aws s3 cp /data s3://test-bucket --recursive --endpoint-url $ENDPOINT"]
      envFrom:
        - secretRef:
            name: minio-conf # you need to create a file like minio-conf.yaml
