apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli
     # command: ["/bin/sh","-c","mkdir -p /data/uid && curl -LO https://dax-cdn.cdn.appdomain.cloud/dax-noaa-weather-data-jfk-airport/1.1.4/noaa-weather-data-jfk-airport.tar.gz -P  /tmp && tar -xf /tmp/noaa-weather-data-jfk-airport.tar.gz -C /data/uid && rm -rf /tmp/noaa-weather-data-jfk-airport.tar.gz && aws s3api create-bucket uid --endpoint-url $ENDPOINT"]
      command: ["/bin/sh","-c","aws s3api create-bucket --bucket uid3 --endpoint-url $ENDPOINT && mkdir /data && touch /data/file1 && touch /data/file2 && aws s3 cp /data s3://uid3 --recursive --endpoint-url $ENDPOINT"]
      envFrom:
        - secretRef:
            name: minio-conf # you need to create a file like minio-conf.yaml
